name = "my-personal-blog"
compatibility_date = "2024-01-15"

# Pages 构建配置
pages_build_output_dir = "out"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "personal-blog-db"
database_id = "8c5d09bc-b310-4d6b-8bce-2a3c0c585e74" 